import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,existsSync} from "node:fs";
const read=p=>readFileSync(new URL("../"+p,import.meta.url),"utf8");
const pages=["index.html","participar.html","midia.html","campori.html","lava-jato.html","painel-lideranca.html","painel-unidade.html"];
test("páginas mantidas existem",()=>{for(const p of pages)assert.ok(existsSync(new URL("../"+p,import.meta.url)),p)});
test("páginas retiradas não estão no menu ou cache",()=>{for(const p of ["agenda.html","unidades.html","aventuras.html","projetos.html"]){assert.ok(!read("sw.js").includes('"./'+p+'"'));assert.ok(!read("assets/js/main.js").includes('href: "'+p+'"'))}});
test("localização informada pelo clube",()=>{assert.ok(read("participar.html").includes("https://maps.app.goo.gl/DDrkQvhriKhxUoJQA"))});
test("calendário interno continua disponível",()=>{assert.ok(read("painel-lideranca.html").includes("planejamento-clube"))});
test("página de participação tem navegação e versão mobile",()=>{const s=read("participar.html");assert.match(s,/data-site-header/);assert.match(s,/name="viewport"/)});
