import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
const root=new URL("../",import.meta.url);
const read=p=>readFileSync(new URL("../"+p,import.meta.url),"utf8");
const pages=["index.html","agenda.html","unidades.html","participar.html","projetos.html","aventuras.html","midia.html","campori.html","lava-jato.html","painel-lideranca.html","painel-unidade.html"];
test("páginas públicas e painéis existem",()=>{for(const p of pages)assert.ok(existsSync(new URL("../"+p,import.meta.url)),p)});
test("páginas novas têm idioma, viewport, título e navegação",()=>{for(const p of pages.slice(1,6)){const s=read(p);assert.match(s,/lang="pt-BR"/);assert.match(s,/name="viewport"/);assert.match(s,/<title>/);assert.match(s,/data-site-header/);assert.match(s,/data-site-footer/)}});
test("agenda pública usa coleção isolada e filtra eventos publicados",()=>{const js=read("assets/js/agenda-publica.js");assert.match(js,/eventosPublicos/);assert.match(js,/where\("publicado","==",true\)/);assert.doesNotMatch(js,/planejamentoClube/);assert.match(read("firestore.rules"),/resource\.data\.publicado == true/)});
test("calendário interno permanece privado",()=>{assert.match(read("firestore.rules"),/match \/planejamentoClube\/\{eventoId\} \{\s*allow read: if estaLogado\(\)/)});
test("agenda tem publicação protegida na liderança",()=>{assert.match(read("painel-lideranca.html"),/id="form-evento-publico"/);assert.match(read("assets/js/publicar-agenda.js"),/exigirSessao\("lideranca"/)});
test("service worker inclui páginas novas",()=>{const sw=read("sw.js");for(const p of pages.slice(1,6))assert.ok(sw.includes('"./'+p+'"'),p)});
test("nenhum cadastro de menores aparece nas páginas públicas novas",()=>{for(const p of pages.slice(1,6)){const s=read(p);assert.doesNotMatch(s,/NOMES_UNIDADES|watchMembros|watchPresencas|responsavel2Telefone/)}});